[2018-03-04 19:56:11] errors.ERROR: {"response":"No Access","status":403,"logger":{"context":"HttpException","isTimeDiffEnabled":false}}
[2018-03-04 19:56:35] errors.ERROR: Error: Weather api response error
    at WeatherService.<anonymous> (C:\dev\magenta-test-app\src\services\weather.service.ts:23:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\magenta-test-app\src\services\weather.service.ts:14:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-03-04 20:09:06] errors.ERROR: {"response":"No Access","status":403,"logger":{"context":"HttpException","isTimeDiffEnabled":false}}
[2018-03-04 20:09:16] errors.ERROR: Error: Weather api response error
    at WeatherService.<anonymous> (C:\dev\magenta-test-app\src\services\weather.service.ts:23:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\magenta-test-app\src\services\weather.service.ts:14:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-03-04 20:10:21] errors.ERROR: Error: Weather api response error
    at WeatherService.<anonymous> (C:\dev\magenta-test-app\src\services\weather.service.ts:23:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\magenta-test-app\src\services\weather.service.ts:14:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-03-04 20:12:32] errors.ERROR: Error: Weather api response error
    at WeatherService.<anonymous> (C:\dev\magenta-test-app\src\services\weather.service.ts:23:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\magenta-test-app\src\services\weather.service.ts:14:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-03-04 22:19:31] errors.ERROR: {"response":"No Access","status":403,"logger":{"context":"HttpException","isTimeDiffEnabled":false}}
[2018-03-05 12:04:03] errors.ERROR: TypeError: Cannot read property 'email' of undefined
    at AuthController.<anonymous> (E:\dev\magenta-test-app\src\controllers\auth.controller.ts:40:35)
    at next (native)
    at E:\dev\magenta-test-app\src\controllers\auth.controller.ts:19:71
    at __awaiter (E:\dev\magenta-test-app\src\controllers\auth.controller.ts:15:12)
    at AuthController.logout (E:\dev\magenta-test-app\src\controllers\auth.controller.ts:51:16)
    at RouterExecutionContext.<anonymous> (E:\dev\magenta-test-app\node_modules\@nestjs\core\router\router-execution-context.js:52:33)
    at next (native)
    at fulfilled (E:\dev\magenta-test-app\node_modules\@nestjs\core\router\router-execution-context.js:4:58)
[2018-03-05 17:30:45] errors.ERROR: {"response":"Incorrect login data","status":403,"logger":{"context":"HttpException","isTimeDiffEnabled":false}}
[2018-03-05 23:10:39] errors.ERROR: TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\dev\magenta-test-app\node_modules\generic-pool\lib\ResourceRequest.js:62:17)
    at Timeout.bound (C:\dev\magenta-test-app\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
[2018-03-05 23:10:39] errors.ERROR: SequelizeConnectionError: connect ETIMEDOUT
    at Utils.Promise.tap.then.catch.err (C:\dev\magenta-test-app\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:149:19)
    at tryCatcher (C:\dev\magenta-test-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
[2018-03-05 23:10:47] errors.ERROR: SequelizeConnectionError: connect ETIMEDOUT
    at Utils.Promise.tap.then.catch.err (C:\dev\magenta-test-app\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:149:19)
    at tryCatcher (C:\dev\magenta-test-app\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\magenta-test-app\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\magenta-test-app\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
[2018-03-06 00:00:05] errors.ERROR: Error: Weather api response error
    at WeatherService.<anonymous> (C:\dev\magenta-test-app\src\services\weather.service.ts:54:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\dev\magenta-test-app\src\services\weather.service.ts:14:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
